### ISSUE TITLE
New project changed_cookbooks detection broken

### ISSUE THREAD

**Issue by ndobson** [opscode-cookbooks/delivery-truck#8]
Once a project is merged and the build stage is triggered, we are seeing ```undefined method `[]' for nil:NilClass``` when referencing ```changed_cookbooks```. Looking at the code [here](https://github.com/opscode-cookbooks/delivery-truck/blob/master/libraries/helpers.rb#L182) it seems like a first merge problem, the build stage passes after subsequent merges. My guess is that there isn't a 2nd to last merge in master and that's the issue.

**Comment by tduffield** [comment]
Oh that is an interesting problem. We've been working on a few updates that should address this problem though. I'll keep this issue open to track it.

**Comment by tduffield** [comment]
v1.99.0 should address this issue.

**Comment by ndobson** [comment]
Awesome, thanks @tduffield

**Comment by afiune** [comment]
I am closing this issue in favor of the v`1.99.0` .. If the problem persist we can re-open it. :smile:
