### ISSUE TITLE
delivery-sugar cookbook - proposed switch to https git instead of ssh

### ISSUE THREAD

**Issue by mvillis** [opscode-cookbooks/delivery-truck#9]
The recent inclusion of delivery-sugar has prevented us from using your latest changes as this cookbook is not public: 

```
cookbook 'delivery-sugar', github: 'chef-cookbooks/delivery-sugar'
```

Am I missing something?

Mike.

**Comment by Skippwaahh** [comment]
Mike it seems like that when the guys changed it to use github, delivery-truck uses this URL by default "git://github.com/chef-cookbooks/delivery-sugar.git".

Is it possible to have a http/https option available?

Cheers,
Matt

**Comment by afiune** [comment]
Hi @mvillis ! :smile: 

It looks like it is public: https://github.com/chef-cookbooks/delivery-sugar 

So I would love to see the error you have to help you. (or fix any problem we might have)

**Comment by mvillis** [comment]
Hey @afiune !

If you remember - we had to switch to use https instead of git (proxy blocks the github ssh port).
```
Berkshelf command failed
STDOUT: Resolving cookbook dependencies...
Fetching 'delivery-sugar' from git://github.com/chef-cookbooks/delivery-sugar.git (at master)

STDERR: Git error: command `git clone git://github.com/chef-cookbooks/delivery-sugar.git "/var/opt/delivery/workspace/.berkshelf/.cache/git/8bd38c7af425d85fc5584e936d70713f64290922" --bare --no-hardlinks` failed. If this error persists, try removing the cache directory at '/var/opt/delivery/workspace/.berkshelf/.cache/git/8bd38c7af425d85fc5584e936d70713f64290922'.Output from the command:

fatal: Unable to look up github.com (port 9418) (Name or service not known)
```
Would it be possible to switch over to https?
I've made a proposed change similar to how we did it in delivery-cluster https://github.com/opscode-cookbooks/delivery-cluster/blob/master/Berksfile#L10-L12

**Comment by afiune** [comment]
(awyeah) @mvillis  I remember... Could you give this branch a try? 

https://github.com/opscode-cookbooks/delivery-truck/tree/afiune/berks-depends-on-https

If you have a cookbook you can test, in the `.delivery/config.json` point to the branch `berks-depends-on-https` like this:

```
{
  "version": "2",
  "build_cookbook": {
    "name": "delivery-truck",
    "git": "https://github.com/opscode-cookbooks/delivery-truck.git",
    "branch": "berks-depends-on-https"
  }
}
```

**Comment by mvillis** [comment]
all good (already tested it on a fork of my own) however to be safe also tested on your branch.

worked like a charm!! :-) --> though the branch name is ```afiune/berks-depends-on-https```

fyi - a pull request is already waiting for you to approve if you're happy:
https://github.com/opscode-cookbooks/delivery-truck/pull/10

**Comment by afiune** [comment]
Closing this in favor of https://github.com/opscode-cookbooks/delivery-truck/pull/10 

Great Job @mvillis !! :+1:
